version: '3.7'


services:
  db:
    image: lhk810/mysql
    build:
      context: ../
      dockerfile: docker/Dockerfile.mysql
    volumes:
      - mysql-volume:/var/lib/mysql
        # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    container_name: my_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - SPRING_PASSWORD=${SPRING_PASSWORD}
    ports: 
      - target: 3306
        published: 3306
        protocol: tcp
        mode: host

  spring-boot:
    image: lhk810/daily-report-spring
    restart: always
    container_name: my_spring-boot
    depends_on:
      - db
    environment:
      - SPRING_PASSWORD=${SPRING_PASSWORD}
      - MYSQL_HOST=db
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host


volumes:
  mysql-volume:
